apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: security-check-java-{{ .Chart.Version }}
spec:
  templates:
    - name: security-check
      inputs:
        artifacts:
          - name: repo
            path: /src
      container:
        image: aquasec/trivy
        command: ["trivy"]
        args: ["fs", "--exit-code", "1", "--severity", "HIGH,CRITICAL", "/src"]
