apiVersion: v2
name: pr-pipeline-chart
version: 1.0.0
description: Umbrella chart for Argo Workflows
dependencies:
  - name: build-step-chart
    version: 0.1.0
    repository: oci://ghcr.io/niharbabu99
  - name: security-check-chart
    version: 0.1.0
    repository: oci://ghcr.io/niharbabu99
  - name: image-creation-chart
    version: 0.1.0
    repository: oci://ghcr.io/niharbabu99

