apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: image-creation
spec:
  templates:
    - name: image-build
      inputs:
        artifacts:
          - name: repo
            path: /src
      container:
        image: aquasec/trivy
        command: ["sh", "-c"]
        args: ["ls -al /src && echo \"imagecreation is successful\""]
        #"fs", "--exit-code", "1", "--severity", "HIGH,CRITICAL", "ls -al /src"]
