apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: {{ .Values.workflowTemplate.name }}
spec:
  templates:
    - name: image-build
      inputs:
        artifacts:
          - name: repo
            path: /src
      container:
        image: aquasec/trivy
        command: ["trivy"]
        args: ["ls -al /src"]
        #"fs", "--exit-code", "1", "--severity", "HIGH,CRITICAL", "ls -al /src"]
