apiVersion: argoproj.io/v1alpha1
kind: ClusterWorkflowTemplate
metadata:
  name: build-step-{{ .Chart.Version }}
spec:
  templates:
    - name: java-build
      inputs:
        artifacts:
          - name: repo
            path: /src
            git:
              repo: "https://github.com/niharbabu99/{{`{{workflow.parameters.git_repo_name}}`}}.git"
              revision: "{{`{{workflow.parameters.git-revision}}`}}"
              disableSubmodules: true
              depth: 1
      outputs:
        artifacts:
          - name: repo
            globalName: repo
            path: /src
            archive:
              none: {}
      container:
        image: maven:3.9-eclipse-temurin-17
        command: ["sh", "-c"]
        workingDir: /src
        args: ["pwd && set +x && ls -al /src"]
        #&& mvn clean verify"]
