---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipeline-subcharts
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/niharbabu99/argo-helm-monorepo
    targetRevision: main
    path: ci/subcharts
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ghcr-subcharts-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: build-step-chart
            chart: niharbabu99/build-step-chart
            version: 0.4.0
          - name: security-check-chart
            chart: niharbabu99/security-check-chart
            version: 0.1.0
          - name: image-creation-chart
            chart: niharbabu99/image-creation-chart
            version: 0.1.0
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: default
      source:
        repoURL: ghcr.io
        chart: '{{chart}}'
        targetRevision: '{{version}}'
        helm:
          skipCrds: false
      destination:
        server: https://kubernetes.default.svc
        namespace: argo
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
