apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipeline-subcharts
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/niharbabu99/argo-helm-monorepo
    targetRevision: main
    path: ci/subcharts
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: build-step-chart
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ghcr.io
    chart: niharbabu99/build-step-chart
    targetRevision: 0.1.0
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: security-check-chart
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ghcr.io
    chart: niharbabu99/security-check-chart
    targetRevision: 0.1.0
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: image-creation-chart
  namespace: argocd
spec:
  project: default
  source:
    repoURL: ghcr.io
    chart: niharbabu99/image-creation-chart
    targetRevision: 0.1.0
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

