apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: {{ .Release.Name }}-pr-pipeline
  namespace: argo
spec:
  entrypoint: run-pr-pipeline
  serviceAccountName: argo
  arguments:
    parameters:
      - name: git_repo_name
        value: "{{ .Values.build.parameters.git_repo_name }}"
      - name: git_revision
        value: "{{ .Values.build.parameters.git_revision }}"
  templates:
    - name: run-pr-pipeline
      steps:
        - - name: build
            templateRef:
              name: build-step
              template: java-build
              clusterScope: true
            arguments:
              parameters:
                - name: git_repo_name
                  value: "{{ `{{workflow.parameters.git_repo_name}}` }}"
                - name: git_revision
                  value: "{{ `{{workflow.parameters.git_revision}}` }}"
        - - name: security
            templateRef:
              name: security-check-java
              template: security-check
              clusterScope: true
            arguments:
              artifacts:
                - name: repo
                  from: "{{ `{{workflow.outputs.artifacts.repo}}` }}"
        - - name: image
            templateRef:
              name: image-creation
              template: image-build
              clusterScope: true
            arguments:
              artifacts:
                - name: repo
                  from: "{{ `{{workflow.outputs.artifacts.repo}}` }}"

